######  Python  ###########
#Joseph Mulray, Assingment 4 Makefile
#Bank Transactions
#December 4 2016

.PHONY : build view clean

build :
	@# "Python Makefile"
	chmod +x accounts

view :
	@\less accounts

clean :
	@\rm *.pyc

